### ISSUE TITLE
Add Bootrstrap 4 - Grid component

### ISSUE THREAD

**Issue by tikkat** [justarrived/justarrived.github.io#109]
I fix i fix / Tikkasaurus

- [ ] Add Bootstrap 4 - Grid component dependency
- [ ] Verify that there hasn't been any name/styling collisions
- [ ] Verify that we can "flip"/"mirror" the grid on RTL-locales

**Comment by buren** [comment]
We should only add the components we need. Bootstrap is a large framework that has _a lot of opinions_ on how things should be styled. Including other components will cause problems (and slow down the site a bit..).

We should also make sure we can support the grid "flipping over" on RTL-locales.

**Comment by tikkat** [comment]
Done, here's a PR:
https://github.com/justarrived/justarrived.github.io/pull/112
