### ISSUE TITLE
Make edits to Xmas-campaign page

### ISSUE THREAD

**Issue by perclingweld** [justarrived/justarrived.github.io#126]
- [x] Alla formulärfält ska vara obligatoriska
- [x] Vid submit: Man ska redirectas till landningssidan med ett “Tack för att du vill bidra till att nyanlända ska få #enfotin på arbetsmarknaden! Vi hör av oss i början av det nya året för att föra samtalet vidare.” Just nu hamnar man på en blank "https://www.salesforce.com/servlet/servlet.WebToLead?encoding=UTF-8”
- [x] Supporters-listan verkar inte funka och ej heller countern
- [x] Önskar att bild-sektionen ska täcka 100% av skärmbredden och lika dikt an mot varandra.
- [x] Ändra URL:en till “justarrived.se/decemberutmaningen"
- [x] ~Går det att göra så att bilderna på de tecknade figurerna syns i mobilversionen också?~ See https://github.com/justarrived/justarrived.github.io/issues/130

**Comment by perclingweld** [comment]
- [x] Lägg till Event-tracker för Google Analytics för klick på knappen samt "submits".

**Comment by buren** [comment]
All done, moved the last remaining task/question to its own issue see #130.

**Comment by perclingweld** [comment]
På "Thank-you-sidan"

- [ ] Dela på Facebook/Twitter

- [ ] Tillbaka till kampanjsidan

**Comment by perclingweld** [comment]
Styling på kampanjsidan för mobile:

- [ ] Gör roll och företag i "Senaste supporters" non-bold och skapa mer padding på vänster/höger sida mellan lista/kant på telefon. Dra också ner textstorleken litegrann.
- [ ] Skapa mer blått utrymme ovanför och under "Välkommen hit och god jul!"
- [ ] Se till att ord i textstyckena inte bryts mitt i (kör på hela ord) - du kan dra ner paddingen på sidorna till hälften av av vad den är nu.
- [ ] Ta bort lite vit padding ovanför och under counter
