### ISSUE TITLE
Fixar på kampanjsidan

### ISSUE THREAD

**Issue by perclingweld** [justarrived/justarrived.github.io#138]
<img width="777" alt="screen shot 2016-12-09 at 14 42 00" src="https://cloud.githubusercontent.com/assets/22094652/21050946/0ac7ca44-be1e-11e6-9fba-4a1ed3150bce.png">

Ska vara "får".

<img width="816" alt="screen shot 2016-12-09 at 14 43 50" src="https://cloud.githubusercontent.com/assets/22094652/21050955/210ff8a8-be1e-11e6-9018-6a25a1b3ceb0.png">

Ta bort den markerade texten helt. Steg 1, 2 och 3 ersätter denna. Gör gärna denna punktlista lite snyggare, dvs lite tajtare och mer som en ul/li.

<img width="840" alt="screen shot 2016-12-09 at 14 43 56" src="https://cloud.githubusercontent.com/assets/22094652/21050988/4e541fa6-be1e-11e6-87a9-0c171474e985.png">

Lägg till "Läs vårt blogginlägg (länka till blogginlägg) om Decemberutmaningen."

**Comment by buren** [comment]
Closed in 8504a87
