### ISSUE TITLE
Add text "Skicka in" to button on register interest

### ISSUE THREAD

**Issue by thenrik** [justarrived/justarrived.github.io#143]
![screenshot 2016-12-09 at 16 44 28 - display 2](https://cloud.githubusercontent.com/assets/22477699/21054681/e7a9b660-be2e-11e6-9a32-de42946a9145.png)

When entering company information, the button on the bottom has no text.
I think it should be added in swedish: Skicka in
English: Submit
http://justarrived.se/decemberutmaningen/

**Comment by buren** [comment]
This has now been fixed. Thank you 👍
