### ISSUE TITLE
Uppdatera sociala delningsknappar på tack-sidan #enfotin

### ISSUE THREAD

**Issue by perclingweld** [justarrived/justarrived.github.io#152]
- [ ] Ändra pre-populated budskap att dela till: "Vårt företag antog precis Decemberutmaningen - att hjälpa fler nyanlända få #enfotin på arbetsmarknaden. Utmana ert företag att göra detsamma!”

- [ ] Lägg till länken: http://justarrived.se/decemberutmaningen så att man delar kampanjsidan och inte tacksidan.

**Comment by buren** [comment]
🙌 @tikkat
