### ISSUE TITLE
Ändra text på kampanjsidan

### ISSUE THREAD

**Issue by perclingweld** [justarrived/justarrived.github.io#153]
- [x] Ändra "supportrar" till "supporters" i rubriken ovanför listan med namn

- [x] Under "För dig som privatperson"

1. **Ta en bild** - Du tar en bild med din smartphone på din fot med sko på (gärna vid en tröskel).

2. **Få bilden redigerad** - Du emailar bilden till hej@justarrived.se.

3. **Lägg upp i sociala medier** - Du får tillbaka den redigerad och med en instruktion om hur du postar den under hashtaggen #enfotin i sociala medier och skickar vidare Decemberutmaningen.

**Comment by tikkat** [comment]
Done
