### ISSUE TITLE
Add the new core team members to Justarrived.se

### ISSUE THREAD

**Issue by perclingweld** [justarrived/justarrived.github.io#158]
Neven Jugo
Lova Westlund
Per Strängberg

+ fler?

**Comment by buren** [comment]
<img width="719" alt="screen shot 2016-12-29 at 20 23 26" src="https://cloud.githubusercontent.com/assets/922411/21552843/af7a63a8-ce04-11e6-96e3-878a5b59d7d6.png">


Starting point https://github.com/justarrived/justarrived.github.io/pull/160

**Comment by buren** [comment]
Added and deployed :shipit: the above ☝️

Created #161 for the final task of adding real images, closing this one..
