### ISSUE TITLE
Implement successful stories section

### ISSUE THREAD

**Issue by Ekman1991** [justarrived/justarrived.github.io#189]
### Definition of done:
![success](https://cloud.githubusercontent.com/assets/3898301/23745890/3f5abbda-04ba-11e7-8e8d-2b5c8e632d46.png)

**Comment by bellevik** [comment]
![success](https://cloud.githubusercontent.com/assets/3898301/23745833/03f1becc-04ba-11e7-8df4-80d5f210d701.png)

**Comment by buren** [comment]
ℹ️ I haven't seen the page that "Read more" would link to. cc @tikkat, @andrew-hawari

**Comment by bellevik** [comment]
Closing, since this section won't be needed
