### ISSUE TITLE
Implement current jobs section

### ISSUE THREAD

**Issue by Ekman1991** [justarrived/justarrived.github.io#190]
### Definition of done:
![current](https://cloud.githubusercontent.com/assets/3898301/23745872/2e06e016-04ba-11e7-9548-1132375d4a44.png)

**Comment by bellevik** [comment]
![current](https://cloud.githubusercontent.com/assets/3898301/23745862/201fd6e2-04ba-11e7-997c-2dc5dce98802.png)

**Comment by bellevik** [comment]
Closing, since this section won't be needed
