### ISSUE TITLE
Redesign header

### ISSUE THREAD

**Issue by bellevik** [justarrived/justarrived.github.io#192]
### Definition of done:
![header](https://cloud.githubusercontent.com/assets/3898301/23746141/2b8bf0aa-04bb-11e7-9088-920e52546448.png)

**Comment by buren** [comment]
This can be done last.. we can keep the cards that we have, _while implementing_ the rest of the designs and when that is done we can do this one..

**Comment by buren** [comment]
See #188 for the navbar task, this task is only for the content "beneath" the navbar.
