### ISSUE TITLE
Redesign job cards section

### ISSUE THREAD

**Issue by Ekman1991** [justarrived/justarrived.github.io#193]
### Definition of done:

<img width="702" alt="screen shot 2017-03-09 at 11 26 00" src="https://cloud.githubusercontent.com/assets/3540718/23746146/356c527c-04bb-11e7-9e7b-403bebf6c35d.png">

**Comment by buren** [comment]
This can be done last.. we can keep the cards that we have,  _while implementing_ the rest of the designs and when that is done we can do this one..
