### ISSUE TITLE
Redesign newcomer_register section

### ISSUE THREAD

**Issue by Ekman1991** [justarrived/justarrived.github.io#195]
### Definition of done:

<img width="698" alt="screen shot 2017-03-09 at 11 27 16" src="https://cloud.githubusercontent.com/assets/3540718/23746296/b69ee4b8-04bb-11e7-8988-c6533d05ecb6.png">

**Comment by buren** [comment]
ℹ️ This is a mirrored version of #194

**Comment by bellevik** [comment]
Do you mean structure-wise? Since they do contain different information.

**Comment by buren** [comment]
@bellevik yep, just a note that it's basically the same section, but mirrored :)
