### ISSUE TITLE
Update address

### ISSUE THREAD

**Issue by pomle** [justarrived/justarrived.github.io#244]
Setup address for Gothenburg

**Comment by buren** [comment]
https://github.com/justarrived/justarrived.github.io/blob/dev/_includes/footer.html#L38-L40

☝️ current address in footer. Actually it's wrong,
 I've forgotten to update that!

**Comment by buren** [comment]
And the web app https://github.com/justarrived/just-match-web/blob/master/src/app/components/footers/default-footer/default-footer.component.ts#L148-L157
