### ISSUE TITLE
Use some of the tricks described in this guide

### ISSUE THREAD

**Issue by buren** [justarrived/justarrived.github.io#27]
https://mademistakes.com/articles/using-jekyll-2016/

also see this list of popular Jekyll plugin https://planetjekyll.github.io/plugins/top

**Comment by tikkat** [comment]
Awesome! How can we close this issue, when do we see it as done? should you and me sit down and see if we can do something about the tricks they describe @buren ?

**Comment by buren** [comment]
@tikkat sounds good. Created this issue as a placeholder for not forgetting ;)
