### ISSUE TITLE
How-it-works section tweaks

### ISSUE THREAD

**Issue by emmalangstrom** [justarrived/justarrived.github.io#74]
1. ~~Border on desktop: change alpha to 0.06~~
2. ~~Padding left/right between the elements is uneven - even out~~
3. ~~Change Swedish text to match english phrasing~~ (Fixed in Transifex)
4. ~~Change button CTA from Apply to Register application / Registrera ansökan~~
5. ~~Change to white background on the modul. “Want to learn more” section gets background: `#E7E8E9` instead.~~ Will be updated/reviewed later.
6. ~~Change swedish section headline to "Så Fungerar Det".~~ (Fixed in Transifex)

**Comment by buren** [comment]
Personally I'm not sure about the darker background colour, what do you think @emmalangstrom? 

<img width="1285" alt="screen shot 2016-10-13 at 20 37 03" src="https://cloud.githubusercontent.com/assets/922411/19361922/d35179f4-9184-11e6-86ce-a573ece10610.png">

**Comment by emmalangstrom** [comment]
Yes keep the #f6f6f6 on that section for now! I will review color combos later. @buren

**Comment by tikkat** [comment]
@emmalangstrom What is meant with point 1: Border on desktop: change alpha to 0.06?

**Comment by tikkat** [comment]
I do not really understand nr 2 either :)

**Comment by emmalangstrom** [comment]
The borders between the how to steps have an rgba value i want to change, specifically the alpha (opacity) i want it changed to 0.06  = 6% opacity. @tikkat 

Nr 2 means that the padding in between the sections is uneven (see black blocks):
![screen shot 2016-11-10 at 14 18 04](https://cloud.githubusercontent.com/assets/22611328/20178291/c0e9a3b8-a750-11e6-8405-f334225ca34e.png)

And also please remove the justification on the text :) it doesn't look good on a lot of screen sizes, the space between words gets too big and weird. 

Thanks!

**Comment by tikkat** [comment]
@emmalangstrom I've done the changes, just give me a 👍 if it looks good so I didn't miss anything and I'll close the issue

**Comment by buren** [comment]
💤
