### ISSUE TITLE
Flow and clarity tweaks

### ISSUE THREAD

**Issue by emmalangstrom** [justarrived/justarrived.github.io#75]
**Front page:**
Change order of CTA on start page - Newcomers first, Company second
Same with nav menu - Newcomers first, Company second

**For Companies page:**
Change background color on all step by step boxes to: #0069d2
Remove 1st and 3rd "Register interest" button (keep middle button). On mobile place the button after the last step.

**Comment by emmalangstrom** [comment]
Tack @tikkat ! Däremot är fortfarande Companies först i CTA sektionen. Vill ha newcomers först så att den hamnar först i flödet på mobil vy (så de slussas rätt och inte automatklickar på company CTA) då inte alla scrollar så långt ner att de ser båda knapparna.

**Comment by tikkat** [comment]
Förstår, misstolkade issuen! Då löser jag det

**Comment by tikkat** [comment]
Done ✂️

**Comment by buren** [comment]
Awesome 🎉
