### ISSUE TITLE
Arabic design errors

### ISSUE THREAD

**Issue by emmalangstrom** [justarrived/justarrived.github.io#77]
**Element alignment:**

Top heading bar needs to be centered over headline: 
![screen shot 2016-10-13 at 13 37 49](https://cloud.githubusercontent.com/assets/22611328/19347728/997bb5f8-914a-11e6-93b8-04ef0829667f.png)

**Quote section:**  
Align text to left, float quote icon to right (alignment breaks the norm for western/arabic in this section). ALTERNATIVELY: Move image to the right of the text.

**Partners section**
Center align everything (headline, button, names, logos)
![screen shot 2016-10-13 at 13 45 46](https://cloud.githubusercontent.com/assets/22611328/19347883/626cb796-914b-11e6-937e-b4a7e93824a0.png)

**Footer section**
Align text to the right.
![](https://files.slack.com/files-pri/T0CVDHN3F-F2NC7V0Q2/page_footer.jpg)

**COMPANY PAGE**

**Step by step section**
Change order of step elements on tablet/desktop (left to right: 3,2,1).
![screen shot 2016-10-13 at 13 48 36](https://cloud.githubusercontent.com/assets/22611328/19347952/cca09e34-914b-11e6-80d9-184d7af10931.png)

**This is just arrived section**
Center align heading and heading bar.
On Mobile: Move icons to right side.

**Job card section**
Align heading bar to center.

**Contact section (yazan)**
Align all content to center.

**NEWCOMERS PAGE**

**Want to know more section**
Center align all content.

**Contact section (anna)**
Center align all content.

**ABOUT PAGE:**
Center align top heading (meet the team) and button under main text (we're hiring).

**Contribute section**
Center align content

**Contact section**
Center align heading + heading bar.

**Partners and enablers**
Center align all content.

**BLOG PAGE**
Keep original layout! (Unless we're planning to translate all blog posts)

**Comment by emmalangstrom** [comment]
@buren Grymt jobbat!! 

2 saker fattas bara: 
**Quote section:**
Align text to left, float quote icon to right (alignment breaks the norm for western/arabic in this section). ALTERNATIVELY: Move image to the right of the text.

**COMPANY PAGE
Step by step section**
Change order of step elements on tablet/desktop (left to right: 3,2,1).

**Comment by buren** [comment]
**Step by step section**: ✅ (e7f60ba)

<img width="1287" alt="screen shot 2016-10-30 at 10 05 41" src="https://cloud.githubusercontent.com/assets/922411/19835476/782c99a8-9e88-11e6-84ef-7f167eea1fdc.png">

**Comment by buren** [comment]
**Quote section**: ✅ (0da424f)

<img width="798" alt="screen shot 2016-10-30 at 17 13 20" src="https://cloud.githubusercontent.com/assets/922411/19837905/2dc971e2-9ec4-11e6-8a6a-fe596762a5c9.png">

**Comment by buren** [comment]
@emmalangstrom ☝️ ✅
