### ISSUE TITLE
Problem with Alignment on how it works page (Arabic)

### ISSUE THREAD

**Issue by xEPIx** [justarrived/justarrived.github.io#85]
The image below how the (dots) aligned wrongly. it should be on left side as shown in image:

![321](https://cloud.githubusercontent.com/assets/16858071/19519670/41993352-960d-11e6-8891-a752acc1a36a.jpg)

on the same page, the numbering should be aligned on the right side, same goes to paragraphs, as shown in image: 

Note: after fixing the paragraphs, please make sure also the dots is on the left side. 

![123](https://cloud.githubusercontent.com/assets/16858071/19519735/84c12af4-960d-11e6-9201-ff682435fcc0.jpg)

**Comment by buren** [comment]
@xEPIx awesome bug report! Thanks 👍 

cc @tikkat

**Comment by buren** [comment]
> Note: after fixing the paragraphs, please make sure also the dots is on the left side. 
> 
> ![123](https://cloud.githubusercontent.com/assets/16858071/19519735/84c12af4-960d-11e6-9201-ff682435fcc0.jpg)

has been fixed by #88

**Comment by xEPIx** [comment]
Thank you @buren
