### ISSUE TITLE
Aligning and correcting the Arabic after latest deploy

### ISSUE THREAD

**Issue by annahornmark** [justarrived/justarrived.github.io#87]
- [x] A lot of issues with aligning the Arabic after latest deploy.

http://justarrived.se/ar/
- [x] 1. Everything underlined should go either from right to left or from left to right. (The small ones are the dots)
  ![image](https://cloud.githubusercontent.com/assets/21364952/19590549/d28497c4-9772-11e6-9143-469cb9cf4960.png)
- [x] 2. dot and Just Arrived switch places
  ![image](https://cloud.githubusercontent.com/assets/21364952/19590423/11368348-9772-11e6-9717-99ea61c5976f.png)
- [x] 3. Everything (in arabic) needs to align right, plus one more issue with "Just Arrived". **OBS! This is the same on all pages!!**
  ![image](https://cloud.githubusercontent.com/assets/21364952/19590488/7d3a0312-9772-11e6-9534-cb485238b4d5.png)

http://justarrived.se/ar/newcomer/
- [x] 1. This one is tricky, but I think I got it right. The numbers indicate in what order the different parts of the sentence should be written. And the order being from right to left. (5 is the dot;)
  ![image](https://cloud.githubusercontent.com/assets/21364952/19590885/8326f12a-9774-11e6-96f5-f5ecdf9321c5.png)
- [x]  2. I've uploaded pictures below this one on how the text should look. The numbers on the headlines need to be to the right. This issue could also be avoided by using arabic numbers in this instance.
  ![image](https://cloud.githubusercontent.com/assets/21364952/19591172/efcd6dda-9775-11e6-87a3-310be8f27ebe.png)
  The texts as they should look, ping me if you need help with knowing if it comes out right;)
- [x] Number 1:
  ![image](https://cloud.githubusercontent.com/assets/21364952/19591133/bb1bf52a-9775-11e6-83e0-3bef3754351b.png)
  Number 2 is good
- [x] Number 3:
  ![image](https://cloud.githubusercontent.com/assets/21364952/19591110/a1d574b0-9775-11e6-96a8-c9826cfc9add.png)
- [x] Number 4: 
  ![image](https://cloud.githubusercontent.com/assets/21364952/19591244/3bd853ca-9776-11e6-8209-5638586c31ba.png)

http://justarrived.se/ar/company/
- [x]  1.
  ![image](https://cloud.githubusercontent.com/assets/21364952/19591313/aeec58fc-9776-11e6-9381-a6d98ae7e68a.png)
- [x] 2. Everything should align right, once again my recommendation is to switch to arabic numbers in the headlines. plus all the dots;)
  ![image](https://cloud.githubusercontent.com/assets/21364952/19591404/2c615b84-9777-11e6-8593-4c1cef36061a.png)
  - [x] 3. ![image](https://cloud.githubusercontent.com/assets/21364952/19591507/b9654310-9777-11e6-9c70-7d4dc3313cb6.png)
- [x] 4. Everything needs to align right, the content is good, but the dots need to be moved. 
  ![image](https://cloud.githubusercontent.com/assets/21364952/19591622/37a29d90-9778-11e6-8e7b-0374b28e4f08.png)
- [x] 5. The Väsbyhem quote: same instructions as the landing page;)

http://justarrived.se/ar/about-us/
- [x] 1. Once again, could be tricky. The text around "Just Arrived" jumps around. 
  ![image](https://cloud.githubusercontent.com/assets/21364952/19592393/d6a8d5d2-977b-11e6-8f8c-fbb45acce0fd.png)
  this is the text in the right order:
  ![image](https://cloud.githubusercontent.com/assets/21364952/19592343/90563f98-977b-11e6-8ee8-2361bba79eba.png)
- [x] 2. Right aligning, and switch places on a couple of names
  ![image](https://cloud.githubusercontent.com/assets/21364952/19592447/1876c6b8-977c-11e6-8cbf-4021fd4667cd.png)
- [x] 3. Right aligning and correcting the content around names.
  ![image](https://cloud.githubusercontent.com/assets/21364952/19592539/8dcd9f36-977c-11e6-91b7-e8363235f0a3.png)
- [x] 4. Needs center alignment
  ![image](https://cloud.githubusercontent.com/assets/21364952/19592590/c4a04cfc-977c-11e6-8156-2caea82f3923.png)

**Comment by buren** [comment]
http://justarrived.se/ar/
- [x] **Number 1/2**

<img width="1081" alt="screen shot 2016-10-22 at 11 40 23" src="https://cloud.githubusercontent.com/assets/922411/19618507/62f1cc30-984c-11e6-82cc-10004fd59914.png">

**Comment by buren** [comment]
http://justarrived.se/ar/newcomer/
- [x] **Number 1.**

<img width="600" alt="screen shot 2016-10-22 at 11 41 34" src="https://cloud.githubusercontent.com/assets/922411/19618510/9a2e03e4-984c-11e6-95f4-48730a5bc809.png">
- [x] **Number 2**

<img width="1281" alt="screen shot 2016-10-22 at 11 42 28" src="https://cloud.githubusercontent.com/assets/922411/19618512/a809a7fc-984c-11e6-869e-222e9e3f4282.png">

**Comment by buren** [comment]
http://justarrived.se/ar/company/
- [x] **Number 1**

<img width="676" alt="screen shot 2016-10-22 at 11 44 00" src="https://cloud.githubusercontent.com/assets/922411/19618520/e54c400c-984c-11e6-80c9-9fe3753685bb.png">
- [x] **Number 2**

<img width="1224" alt="screen shot 2016-10-22 at 11 43 55" src="https://cloud.githubusercontent.com/assets/922411/19618521/e9947a3a-984c-11e6-9363-9817fc4c69f9.png">
- [x] **Number 3**

<img width="1023" alt="screen shot 2016-10-22 at 11 44 45" src="https://cloud.githubusercontent.com/assets/922411/19618523/f90458f0-984c-11e6-88f3-09fbfca1e4f3.png">
- [x] **Number 4**

<img width="579" alt="screen shot 2016-10-22 at 11 45 15" src="https://cloud.githubusercontent.com/assets/922411/19618524/0687e64a-984d-11e6-9a0d-bb3f2c51cff0.png">

**Comment by buren** [comment]
http://justarrived.se/ar/about-us/
-  [ ] **Number 1**

<img width="603" alt="screen shot 2016-10-22 at 11 47 37" src="https://cloud.githubusercontent.com/assets/922411/19618531/617ec1a4-984d-11e6-9d71-1372a96daaab.png">

@annahornmark ☝️ 🆗 ❓ 
- [x] **Number 2**

<img width="347" alt="screen shot 2016-10-22 at 11 48 30" src="https://cloud.githubusercontent.com/assets/922411/19618535/810fcf2c-984d-11e6-92bd-4e14a4634cd4.png">
- [x] **Number 3**

<img width="415" alt="screen shot 2016-10-22 at 11 48 59" src="https://cloud.githubusercontent.com/assets/922411/19618537/9780e020-984d-11e6-80a4-9fdb647eed53.png">
- [x] **Number 4**

<img width="829" alt="screen shot 2016-10-22 at 11 53 38" src="https://cloud.githubusercontent.com/assets/922411/19618551/361d5f1a-984e-11e6-905b-619d23251030.png">

**Comment by buren** [comment]
#89 should have fixed most, if not, all issues mentioned here. I've deployed that to production now, but wont close this issue  until I have confirmation from you @annahornmark or @xEPIx that the site has been fixed.

**Comment by buren** [comment]
@xEPIx confirmed that the issues have been fixed 🎉
