### ISSUE TITLE
Update popup styling

### ISSUE THREAD

**Issue by buren** [justarrived/justarrived.github.io#95]

**Comment by tikkat** [comment]
I've done design changes, it seems like the cards doesn't work on mobile though. Do you have that problem as well @buren ? Is it some kind of jquery that toggles the job cards?

**Comment by buren** [comment]
@tikkat hm.. 🤔 For me (Chrome, Android, Nexus 5) the popups are working. Are none of them working our just the job-cards?

**Comment by tikkat** [comment]
Just the job cards @buren

**Comment by buren** [comment]
@tikkat lets take a quick look on that tomorrow.

**Comment by buren** [comment]
I've created two new issues out of this one.

See: 
- Investigate job cards on mobile not opening their popup #105
- Update popup styling #106

So closing this in favour of those two :)
